# files/nfs-share.sh — TP=3 workers read the head's Hugging Face cache over
# NFSv4 on ConnectX instead of each keeping a local copy of the checkpoint.
#
# Borrowed from ~/NewModels/DS4.1/files/nfs-share.sh (same kit, same author).
# One simplification: DS4.1 keeps its checkpoint outside the HF cache, so it has
# to hardlink-publish into the export tree. GLM's weights already live in the HF
# cache and the containers already mount that cache whole, so the export root IS
# $HF_CACHE_DIR and the NFS device is ":/" — a worker sees
# hub/<repo>/snapshots/<rev> at exactly the path MODEL_DIR already names.
#
# Sourced by start.sh (one worker) and start-tp3.sh (two). Inert unless
# NFS_SHARE=1; the flag defaults to 0 in both, so this changes nothing until a
# .env / .env.tp3 turns it on.
#
# A live exporter from another recipe (vllm-fn-nfs / glm53fp8-nfs / dsv41-nfs)
# is reused rather than fought with — a second kernel nfsd will not start.

NFS_IMAGE="${NFS_IMAGE:-glm53-nfs:local}"
NFS_CONTAINER="${NFS_CONTAINER:-glm53-nfs}"
NFS_VOLUME="${NFS_VOLUME:-glm53-weights}"
NFS_DOCKERFILE_DIR="${NFS_DOCKERFILE_DIR:-$SCRIPT_DIR/files/nfs-server}"
NFS_OPTS="${NFS_OPTS:-ro,sync,no_subtree_check,no_root_squash,insecure,fsid=0}"
NFS_OPTS_CLIENT="${NFS_OPTS_CLIENT:-nfsvers=4.2,ro,nconnect=8,rsize=1048576,wsize=1048576,hard,timeo=600}"
NFS_DEVICE="${NFS_DEVICE:-:/}"

# The launcher says which ranks to serve and how to reach them: start.sh has
# one worker and rank-less helpers, start-tp3.sh has two and rank-indexed ones.
NFS_RANKS="${NFS_RANKS:-1}"

nfs_rank_ssh() {
    local r="$1"; shift
    if declare -F worker_ssh_n >/dev/null 2>&1; then
        worker_ssh_n "$r" "$@"
    else
        worker_ssh "$@"
    fi
}

nfs_rank_ip() {
    if declare -F _tp3_rank_ip >/dev/null 2>&1; then
        _tp3_rank_ip "$1"
    else
        printf '%s' "${WORKER_IP:-}"
    fi
}

nfs_rank_label() {
    if declare -F _tp3_ssh_target >/dev/null 2>&1; then
        _tp3_ssh_target "$1"
    else
        printf '%s' "${WORKER_SSH:-worker}"
    fi
}

nfs_clients() {
    printf '%s' "${NFS_CLIENTS:-10.0.0.2,10.0.0.3,10.0.22.0/24,10.0.23.0/24,10.0.33.0/24}"
}

nfs_live_container() {
    docker ps --format '{{.Names}}' \
        | grep -E '^(vllm-fn-nfs|glm53-nfs|glm53fp8-nfs|dsv41-nfs)$' | head -1
}

nfs_rpc_ready() {
    timeout 3 rpcinfo -t "${1:-127.0.0.1}" nfs 4 >/dev/null 2>&1
}

# The head address a given worker rank should mount. Never 10.0.0.1: those are
# loopback aliases and the mount would fall back to the management link, which
# turns a 164 GiB weight load into an overnight job.
#   1. explicit NFS_SERVER_IP_<rank>, else NFS_SERVER_IP
#   2. the CX7 source address this host would use toward that rank's fabric IP
#      (WORKER_FABRIC_IP / WORKER2_FABRIC_IP), else toward its rank IP
nfs_server_ip_for_rank() {
    local r="$1" var explicit peer src
    var="NFS_SERVER_IP_${r}"
    explicit="${!var:-${NFS_SERVER_IP:-}}"
    if [ -n "$explicit" ]; then printf '%s' "$explicit"; return 0; fi
    if [ "$r" = "1" ]; then var="WORKER_FABRIC_IP"; else var="WORKER${r}_FABRIC_IP"; fi
    peer="${!var:-}"
    [ -n "$peer" ] || peer="$(nfs_rank_ip "$r")"
    # || true: an unroutable peer must yield an empty address for the caller to
    # report, not kill the launcher through set -e / pipefail.
    src="$(ip route get "$peer" 2>/dev/null \
        | awk '{for (i=1;i<=NF;i++) if ($i=="src") { print $(i+1); exit }}' || true)"
    printf '%s' "$src"
}

# Union of whatever the exporter already serves with our client list. A live
# vllm-fn-nfs / dsv41-nfs is shared with the other recipes on this kit, so
# overwriting its client list would silently unmount their workers.
nfs_write_exports() {
    local ctn="$1" clients="$2"
    docker exec -e NFS_CLIENTS="$clients" -e NFS_OPTS="$NFS_OPTS" "$ctn" bash -lc '
        set -e
        {
            [ -f /etc/exports ] && sed -n "s|^/export[[:space:]][[:space:]]*\([^(]*\).*|\1|p" /etc/exports
            printf "%s\n" "$NFS_CLIENTS" | tr "," "\n"
        } | tr -d " " | sed "/^$/d" | sort -u > /tmp/glm53-clients
        {
            echo "# generated by glm53-nfs (union of existing + configured clients)"
            while read -r addr; do
                echo "/export ${addr}(${NFS_OPTS})"
            done < /tmp/glm53-clients
        } > /etc/exports.new
        mv /etc/exports.new /etc/exports
        rm -f /tmp/glm53-clients
        exportfs -rav
    ' >/dev/null
}

nfs_ensure_server() {
    local clients live i
    clients="$(nfs_clients)"
    live="$(nfs_live_container || true)"

    if [ -n "$live" ] && nfs_rpc_ready 127.0.0.1; then
        log "NFS already up ($live) — merging rank clients into its exports"
        nfs_write_exports "$live" "$clients"
        NFS_LIVE_CTN="$live"
        return 0
    fi

    [ -d "$NFS_DOCKERFILE_DIR" ] || die "missing $NFS_DOCKERFILE_DIR"
    [ -d "$HF_CACHE_DIR" ] || die "HF cache missing on the head: $HF_CACHE_DIR"

    log "building NFS image $NFS_IMAGE"
    docker build -q -t "$NFS_IMAGE" "$NFS_DOCKERFILE_DIR" >/dev/null
    docker rm -f "$NFS_CONTAINER" >/dev/null 2>&1 || true
    log "exporting $HF_CACHE_DIR over NFSv4 (clients: $clients)"
    docker run -d --name "$NFS_CONTAINER" --restart unless-stopped \
        --privileged --network host \
        -v "$HF_CACHE_DIR:/export:ro" \
        -e "NFS_CLIENTS=$clients" \
        -e "NFS_OPTS=$NFS_OPTS" \
        "$NFS_IMAGE" >/dev/null
    for i in $(seq 1 20); do
        if nfs_rpc_ready 127.0.0.1; then
            log "NFS server ready ($NFS_CONTAINER)"
            NFS_LIVE_CTN="$NFS_CONTAINER"
            return 0
        fi
        sleep 0.5
    done
    docker logs "$NFS_CONTAINER" >&2 || true
    die "NFS server did not become ready. Check: docker logs $NFS_CONTAINER"
}

nfs_ensure_worker_volume() {
    local r="$1" addr
    addr="$(nfs_server_ip_for_rank "$r")"
    [ -n "$addr" ] || die "rank ${r}: cannot resolve a head address to mount — set NFS_SERVER_IP_${r} in .env.tp3"
    case "$addr" in
        10.0.0.*|127.*) die "rank ${r}: resolved head address ${addr} is a loopback alias, not a CX7 address — set NFS_SERVER_IP_${r} in .env.tp3" ;;
    esac
    log "rank ${r} ($(nfs_rank_label "$r")): docker volume ${NFS_VOLUME} -> nfs://${addr}${NFS_DEVICE}"
    nfs_rank_ssh "$r" "
        set -e
        docker volume rm '$NFS_VOLUME' >/dev/null 2>&1 || true
        docker volume create --driver local \
            --opt type=nfs \
            --opt o=addr=${addr},${NFS_OPTS_CLIENT} \
            --opt device=${NFS_DEVICE} \
            '$NFS_VOLUME' >/dev/null
    "
}

# Prove the rank can actually read the snapshot before a 15-minute boot does.
nfs_worker_has_weights() {
    local r="$1" rel
    rel="hub/${MODEL_CACHE_NAME}"
    nfs_rank_ssh "$r" "
        docker image inspect alpine:latest >/dev/null 2>&1 || docker pull alpine:latest >/dev/null
        docker run --rm -v '${NFS_VOLUME}:/m:ro' alpine:latest test -d '/m/${rel}'
    " >/dev/null 2>&1
}

nfs_share_weights() {
    local r
    nfs_ensure_server
    for r in $NFS_RANKS; do
        nfs_ensure_worker_volume "$r"
        if nfs_worker_has_weights "$r"; then
            log "rank ${r}: sees ${MODEL_CACHE_NAME} over NFS"
        else
            die "rank ${r} cannot read ${MODEL_CACHE_NAME} over NFS — check the export ACL covers that rank's fabric subnet, and 'docker logs ${NFS_LIVE_CTN:-$NFS_CONTAINER}'"
        fi
    done
    log "rank(s) ${NFS_RANKS} read the head's HF cache over NFS — no local copy"
}

nfs_unmount_workers() {
    local r
    for r in $NFS_RANKS; do
        nfs_rank_ssh "$r" "docker volume rm '$NFS_VOLUME' >/dev/null 2>&1 || true" || true
    done
}

# What a rank bind-mounts at /root/.cache/huggingface when sharing is on.
nfs_hf_mount_spec() { printf '%s:/root/.cache/huggingface:ro' "$NFS_VOLUME"; }
